[package]
name = "acme_router"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
apollo-router = { git = "https://github.com/apollographql/router", tag = "v0.9.0" }
apollo-router-core = { git = "https://github.com/apollographql/router", tag = "v0.9.0" }
async-trait = "0.1.53"
futures = "0.3.21"
http = "0.2.7"
schemars = "0.8.9"
serde = "1.0.137"
serde_json = "1.0.81"
tokio = "1.18.2"
tower = { version = "0.4.12", features = ["full"] }