version: '3'
services:
  apollo-router-custom-plugin:
    container_name: apollo-router-custom-plugin
    build: ./router/custom-plugin
    volumes:
      - ./supergraph.graphql:/dist/schema/supergraph.graphql
      - ./router/custom-plugin/acme_router.yaml:/dist/config/router.yaml
    command: [ "-c", "config/router.yaml", "-s", "schema/supergraph.graphql", "--log", "info" ]
    ports:
      - "4000:4000"
  products:
    container_name: products
    build: ./subgraphs/products
  inventory:
    container_name: inventory
    build: ./subgraphs/inventory
  users:
    container_name: users
    build: ./subgraphs/users
  pandas:
    container_name: pandas
    build: ./subgraphs/pandas
