# extends supergraph-demo-fed2/docker-compose.yaml
# https://docs.docker.com/compose/extends/#multiple-compose-files

# use 'make up-supergraph-router-rhai' to get started

version: '3'
services:
  apollo-router-rhai:
    container_name: apollo-router-rhai
    build: ./supergraph/router/customizations/rhai
    volumes:
      - ./supergraph/router/customizations/rhai/router.yaml:/dist/config/router.yaml
    command: [ "--dev", "-c", "config/router.yaml", "--log", "info" ]
    env_file: # 'make up-supergraph-router-rhai' saves APOLLO_KEY and APOLLO_GRAPH_REF
      - ./graph-api.env
    environment:
      - APOLLO_OTEL_EXPORTER_HOST=collector
    ports:
      - "4000:4000"