# intended for use with supergraph-demo-fed2/docker-compose.yaml
# https://docs.docker.com/compose/extends/#multiple-compose-files
# paths are relative to the repo root dir
version: '3'
services:
  apollo-gateway:
    container_name: apollo-gateway
    build: ./supergraph/gateway
    env_file: # 'make up-supergraph-gateway' saves APOLLO_KEY and APOLLO_GRAPH_REF
      - ./graph-api.env
    environment:
      - APOLLO_OTEL_EXPORTER_TYPE=collector
      - APOLLO_OTEL_EXPORTER_HOST=collector
      - APOLLO_OTEL_EXPORTER_PORT=4318
    ports:
      - "4000:4000"