# extends supergraph-demo-fed2/docker-compose.yaml
# https://docs.docker.com/compose/extends/#multiple-compose-files

# use 'make up-supergraph-gateway' to get started

version: '3.9'
services:
  apollo-gateway:
    container_name: apollo-gateway
    build: ./supergraph/gateway
    env_file: # 'make up-supergraph-gateway' saves APOLLO_KEY and APOLLO_GRAPH_REF to connect to Studio
      - ./graph-api.env
    environment:
      - APOLLO_OTEL_EXPORTER_TYPE=collector
      - APOLLO_OTEL_EXPORTER_HOST=collector
      - APOLLO_OTEL_EXPORTER_PORT=4318
    ports:
      - "4000:4000"